name: multi_job_workflow
on: push

# this workflow is to verify multiple jobs

jobs:

    build-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: install curl
              run: sudo apt-get install curl
            - name: wait for 30 seconds
              run: sleep 30

    test-job:
        needs: build-job
        runs-on: ubuntu-latest
        steps:
            - name: list all files
              run: ls -lart
            - name: check curl version
              run: curl --version
            - name: wait for 10 seconds
              run: sleep 10

    deploy-job:
        needs: test-job
        runs-on: ubuntu-latest
        steps:
            - name: display all files
              run: ls -lart
