name: multi_job_workflow
on: push

# this workflow is to verify multiple jobs

jobs:

    build-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: install curl
              run: sudo apt-get install curl
            - name: wait for 30 seconds
              run: sleep 30

    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: display README.md content
              run: cat README.md
            - name: wait for 10 seconds
              run: sleep 10

    deploy-job:
        runs-on: ubuntu-latest
        steps:
            - name: display all files
              run: ls -lart
