name: multiple_steps_workflow
on: push

jobs:
    multipleStepJob:
        name: verify multiple steps
        runs-on: ubuntu-latest

        steps:
            - name: checkout first
              uses: actions/checkout@v4

            - name: Welcome KLU
              run: |
                echo "Welcome KLU demo"
                ls -lart
                cat README.md
